backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "index"
    fields:
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published", name: "published", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
